goal_achiever/urls.py
'''
urls for goal_achiever
'''

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^goal_list/$', views.goal_list, name='goal_list'),
    url(r'^goal_list/(?P<goal_id>[0-9]+)/$', views.goal, name='goal'),
    url(r'^add_delete_items/$',
        views.add_delete_items,
        name='add_delete_items'),

    url(r'^task_list/$', views.task_list, name='task_list'),
    url(r'^task_list/(?P<task_id>[0-9]+)/$', views.task, name='task'),

    url(r'^restriction_list/$',
        views.restriction_list,
        name='restriction_list'),
    url(r'^restriction_list/(?P<restriction_id>[0-9]+)/$',
        views.restriction,
        name='restriction'),
]

life_manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^goal_achiever/', include('goal_achiever.urls')),
    url(r'^schedule/', include('schedule.urls')),
    url(r'^admin/', admin.site.urls),
]

schedule/urls.py
'''
urls for schedule
'''

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^schedule_builder/$', views.schedule_builder, name='schedule_builder'),
]

goal_achiever/models.py
'''
goal_achiever models
'''

from django.db import models


class Task(models.Model):
    '''
    a Task model
    '''
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=300, blank=True)

    def __str__(self):
        return self.name


class Restriction(models.Model):
    '''
    a Restriction model
    '''
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=300, blank=True)

    def __str__(self):
        return self.name


class Goal(models.Model):
    '''
    a Goal model
    '''
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=300)
    tasks = models.ManyToManyField(Task, blank=True)
    restrictions = models.ManyToManyField(Restriction, blank=True)

    def __str__(self):
        return self.name

schedule/models.py
from django.db import models

# Create your models here.

goal_achiever/forms.py
'''
forms for createing new goals, tasks and restrictions
'''

from django import forms

from . import models


class NewGoalForm(forms.ModelForm):
    '''
    a form for creating new goals
    '''
    class Meta:
        model = models.Goal
        fields = ('name',
                  'description')


class NewTaskForm(forms.ModelForm):
    '''
    a form for creating new tasks
    '''
    class Meta:
        model = models.Task
        fields = ('name',
                  'description')


class NewRestrictionForm(forms.ModelForm):
    '''
    a form for creating new restrictions
    '''
    class Meta:
        model = models.Restriction
        fields = ('name',
                  'description')

goal_achiever/views.py
'''
goal_achiever views
'''

from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse

from .models import Goal, Restriction, Task
from .forms import NewGoalForm, NewTaskForm, NewRestrictionForm


def goal(request, goal_id):
    '''
    docstring
    '''
    selected_goal = get_object_or_404(Goal, pk=goal_id)
    context = {
        'goal': selected_goal,
    }
    return render(request, 'goal_achiever/goal.html', context)


def add_delete_items(request):
    '''
    save goal list changes
    '''
    if request.method == "POST":
        data = request.POST.copy()
        control = data['control']
        active_class = None
        num_of_items_to_create = int(data['Q'])
        items_to_delete = data.getlist('D[]')
        num_of_items_to_delete = len(items_to_delete)

        try:
            active_item = get_object_or_404(Goal, pk=data['item_pk'])
        except Exception:
            pass

        if control == 'goals':
            active_class = Goal
        elif control == 'tasks':
            active_class = Task
        elif control == 'restrictions':
            active_class = Restriction
        else:
            return JsonResponse({'response': 'error: invalid form control'})

        # create items
        i = 0
        while i is not num_of_items_to_create:
            create_item = {
                'name': data['C[{}][name]'.format(i)],
                'description': data['C[{}][description]'.format(i)],
            }
            if control == 'goals':
                form = NewGoalForm(create_item)
                form.save()
            elif control == 'tasks':
                form = NewTaskForm(create_item)
                form.save()
                active_item.tasks.add(Task.objects.last().pk)
            elif control == 'restrictions':
                form = NewRestrictionForm(create_item)
                form.save()
                active_item.restrictions.add(Restriction.objects.last().pk)

            i = i + 1

        # delete items
        i = 0
        while i is not num_of_items_to_delete:
            instance = get_object_or_404(active_class,
                                         pk=int(items_to_delete[i]))
            instance.delete()
            i = i + 1

        return JsonResponse({'response': 'success'})
    else:
        return JsonResponse({'response': 'error: wrong request'})


def goal_list(request):
    '''
    docstring
    '''
    goals = Goal.objects.all()
    context = {
        'goals': goals,
    }
    return render(request, 'goal_achiever/goal_list.html', context)


def task(request, task_id):
    '''
    docstring
    '''
    selected_task = get_object_or_404(Task, pk=task_id)
    task_goals = selected_task.goal_set.all()
    context = {
        'task': selected_task,
        'task_goals': task_goals,
    }
    return render(request, 'goal_achiever/task.html', context)


def task_list(request):
    '''
    docstring
    '''
    tasks = Task.objects.all()
    context = {
        'tasks': tasks,
    }
    return render(request, 'goal_achiever/task_list.html', context)


def restriction(request, restriction_id):
    '''
    docstring
    '''
    selected_restriction = get_object_or_404(Restriction, pk=restriction_id)
    restriction_goals = selected_restriction.goal_set.all()
    context = {
        'restriction': selected_restriction,
        'restriction_goals': restriction_goals,
    }
    return render(request, 'goal_achiever/restriction.html', context)


def restriction_list(request):
    '''
    docstring
    '''
    restrictions = Restriction.objects.all()
    context = {
        'restrictions': restrictions,
    }
    return render(request, 'goal_achiever/restriction_list.html', context)

schedule/views.py
from django.shortcuts import render
from goal_achiever.models import Task


def schedule_builder(request):
    '''
    docstring
    '''
    tasks = Task.objects.all()
    context = {
        'tasks': tasks,
    }
    return render(request, 'schedule/schedule_builder.html', context)

goal_achiever/templates/goal_achiever/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'goal_achiever/js/goal_achiever.js' %}"></script>
    <script type="text/javascript" src="{% static 'goal_achiever/js/jquery.cookie.js' %}"></script>
    <title>Goal Achiever</title>
    <link rel="stylesheet"  href="{% static 'goal_achiever/css/goal_achiever.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Quicksand&display=swap" rel="stylesheet">
</head>
<body>
    <a href="{% url 'goal_list' %}">-goals-</a>
    <a href="{% url 'task_list' %}">-tasks-</a>
    <a href="{% url 'restriction_list' %}">-restrictions-</a>
    <br>
    ---------------------------------------------------
    {% block content %}
    {% endblock %}
</body>
</html>

goal_achiever/templates/goal_achiever/goal.html
{% extends 'goal_achiever/base.html' %}
{% block content %}
<div id="item-selected" pk="{{ goal.pk }}" item="goal">
  <h1>{{ goal }}</h1>
  <p>{{ goal.description }}</p>
  <br>
</div>
---------------------------------------------------
<br>
<h2>tasks:</h2>
<div class="form-control" name="tasks">
  <button class="edit btn">Edit Task List</button>
  <div class="container-1 container-form">
      <div class="container-2 container-fields">
          <label for="id_name">Name:</label>
          <br>
          <input type="text" name="name", maxlength="50" id="id_name">
          <br>
          <br>
          <label for="id_description">Description:</label>
          <br>
          <textarea type="text" name="description", maxlength="300" id="id_description"></textarea>
          <br>
          <button class="add btn">Add</button>
      </div>
      <div class="container-2 container-btn">
          <button class="save btn">Save</button>
          <button class="cancel btn">Cancel</button>
      </div>
  </div>
  <div class="container-1 container-items">
    <div class="new-items">
        <!-- here appear new (not saved) items -->
    </div>
    <div id="existing-items">
        {% if goal.tasks %}
        {% for task in goal.tasks.all reversed %}
        <div class="container-2 item">
            <a id="item_link-{{ task.pk }}" href="{% url 'task' task.pk %}">
                <span id="item_name-{{ task.pk }}" class="name">{{ task }}</span>
            </a>
            <span class="delete {{ task.pk }}">X</button>
        </div>
        {% endfor %}
        {% else %}
        <p>This goal have no tasks...</p>
        {% endif %}
    </div>
  </div>
</div>
<br>
---------------------------------------------------
<br>
<h2>restrictions:</h2>
<div class="form-control" name="restrictions">
  <button class="edit btn">Edit Restriction List</button>
  <div class="container-1 container-form">
      <div class="container-2 container-fields">
          <label for="id_name">Name:</label>
          <br>
          <input type="text" name="name", maxlength="50" id="id_name">
          <br>
          <br>
          <label for="id_description">Description:</label>
          <br>
          <textarea type="text" name="description", maxlength="300" id="id_description"></textarea>
          <br>
          <button class="add btn">Add</button>
      </div>
      <div class="container-2 container-btn">
          <button class="save btn">Save</button>
          <button class="cancel btn">Cancel</button>
      </div>
  </div>
  <div class="container-1 container-items">
    <div class="new-items">
        <!-- here appear new (not saved) items -->
    </div>
    <div id="existing-items">
        {% if goal.restrictions %}
        {% for restriction in goal.restrictions.all reversed %}
        <div class="container-2 item">
            <a id="item_link-{{ restriction.pk }}" href="{% url 'restriction' restriction.pk %}">
                <span id="item_name-{{ restriction.pk }}" class="name">{{ restriction }}</span>
            </a>
            <span class="delete {{ restriction.pk }}">X</button>
        </div>
        {% endfor %}
        {% else %}
        <p>This goal have no restrictions...</p>
        {% endif %}
    </div>
  </div>
</div>
<br>
---------------------------------------------------
{% endblock %}

goal_achiever/templates/goal_achiever/goal_list.html
{% extends 'goal_achiever/base.html' %}{% load static %}
{% block content %}

<h1>Goals:</h1>
<div class="form-control" name="goals">
  <button class="edit btn">Edit Goal List</button>
  <div class="container-1 container-form goals">
      <div class="container-2 container-fields">
          <label for="id_name">Name:</label>
          <br>
          <input type="text" name="name", maxlength="50" id="id_name">
          <br>
          <br>
          <label for="id_name">Description:</label>
          <br>
          <textarea type="text" name="description", maxlength="300" id="id_description"></textarea>
          <br>
          <button class="add btn">Add</button>
      </div>
      <div class="container-2 container-btn">
          <button class="save btn">Save</button>
          <button class="cancel btn">Cancel</button>
      </div>
  </div>
  <div class="container-1 container-items">
      <div class="new-items">
          <!-- here appear new (not saved) items -->
      </div>
      <div id="existing-items">
          {% if goals %}
          {% for goal in goals reversed %}
          <div class="container-2 item">
              <a id="item_link-{{ goal.pk }}" href="{% url 'goal' goal.pk %}">
                  <span id="item_name-{{ goal.pk }}" class="name">{{ goal }}</span>
              </a>
              <span class="delete {{ goal.pk }}">X</button>
          </div>
          {% endfor %}
          {% else %}
          <p>You have no goals...</p>
          {% endif %}
      </div>
  </div>
</div>
{% endblock %}

goal_achiever/templates/goal_achiever/restriction.html
{% extends 'goal_achiever/base.html' %}

{% block content %}

<h1>{{ restriction }}</h1>
<h3>Description:</h3>
<p>{{ restriction.description }}</p>
---------------------------------------------------
<h2>Goals affected:</h2>
{% for goal in restriction_goals %}
<li><a href="{% url 'goal' goal.pk %}">{{ goal }}</a></li>
{% endfor %}

{% endblock %}

goal_achiever/templates/goal_achiever/restriction_list.html
{% extends 'goal_achiever/base.html' %}
{% block content %}
<h1>Restrictions:</h1>

{% for restriction in restrictions %}
    <li><a href="{% url 'restriction' restriction.pk %}">{{ restriction }}</a></li>
{% endfor %}
{% endblock %}

goal_achiever/templates/goal_achiever/task.html
{% extends 'goal_achiever/base.html' %}

{% block content %}

<h1>{{ task }}</h1>
<h3>Description:</h3>
<p>{{ task.description }}</p>
---------------------------------------------------
<h2>Goals affected:</h2>
{% for goal in task_goals %}
<li><a href="{% url 'goal' goal.pk %}">{{ goal }}</a></li>
{% endfor %}

{% endblock %}

goal_achiever/templates/goal_achiever/task_list.html
{% extends 'goal_achiever/base.html' %}
{% block content %}
<h1>Tasks:</h1>

{% for task in tasks %}
    <li><a href="{% url 'task' task.pk %}">{{ task }}</a></li>
{% endfor %}
{% endblock %}

schedule/templates/schedule/schedule_builder.html
{% block content %}
<h1>schedule builder</h1>

{% for task in tasks %}
<p>{{ task }}</p>
{% endfor %}
{% endblock %}